"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { AlertTriangle, CalendarClock, FileCheck2, Pencil, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { fleetoraApi } from "../lib/api";

type Resource = { id: string; registration_number?: string; full_name?: string };
type Resources = { vehicles: Resource[]; drivers: Resource[] };
type ComplianceDocument = { id: string; vehicle_id: string | null; driver_id: string | null; document_type: string; document_number: string | null; issued_on: string | null; expires_on: string | null; status: string; vehicles?: { registration_number: string } | null; drivers?: { full_name: string } | null };
const blank = { owner_type: "vehicle", vehicle_id: "", driver_id: "", document_type: "insurance", document_number: "", issued_on: "", expires_on: "" };
const types = ["insurance", "rc", "fitness", "permit", "tax", "puc", "license", "pod", "other"];
const today = () => new Date().toISOString().slice(0, 10);
const addDays = (date: string, days: number) => { const value = new Date(`${date}T00:00:00`); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); };

export function DocumentComplianceView() {
  const [rows, setRows] = useState<ComplianceDocument[]>([]); const [resources, setResources] = useState<Resources>({ vehicles: [], drivers: [] });
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [documents, refs] = await Promise.all([fleetoraApi<ComplianceDocument[]>("/documents"), fleetoraApi<Resources>("/resources")]); setRows(documents); setResources(refs); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load compliance documents."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const classified = useMemo(() => rows.map(row => ({ ...row, expiryState: !row.expires_on ? "active" : row.expires_on < today() ? "expired" : row.expires_on <= addDays(today(), 30) ? "expiring" : "active" })), [rows]);
  const expired = classified.filter(row => row.expiryState === "expired").length; const expiring = classified.filter(row => row.expiryState === "expiring").length;
  function add() { setEditing(null); setForm(blank); setOpen(true); }
  function edit(row: ComplianceDocument) { setEditing(row.id); setForm({ owner_type: row.driver_id ? "driver" : "vehicle", vehicle_id: row.vehicle_id ?? "", driver_id: row.driver_id ?? "", document_type: row.document_type, document_number: row.document_number ?? "", issued_on: row.issued_on ?? "", expires_on: row.expires_on ?? "" }); setOpen(true); }
  async function save() { setSaving(true); try { const status = !form.expires_on ? "active" : form.expires_on < today() ? "expired" : form.expires_on <= addDays(today(), 30) ? "expiring" : "active"; const body = { vehicle_id: form.owner_type === "vehicle" ? form.vehicle_id || null : null, driver_id: form.owner_type === "driver" ? form.driver_id || null : null, document_type: form.document_type, document_number: form.document_number || null, issued_on: form.issued_on || null, expires_on: form.expires_on || null, status }; await fleetoraApi(editing ? `/documents/${editing}` : "/documents", { method: editing ? "PATCH" : "POST", body: JSON.stringify(body) }); setOpen(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save document."); } finally { setSaving(false); } }
  async function remove(row: ComplianceDocument) { if (!window.confirm(`Delete ${row.document_type.toUpperCase()} document?`)) return; try { await fleetoraApi(`/documents/${row.id}`, { method: "DELETE" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete document."); } }
  const valid = Boolean(form.document_type && (form.owner_type === "vehicle" ? form.vehicle_id : form.driver_id));
  return <motion.main className="module-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
    <header className="module-header"><div className="module-header-copy"><div className="module-eyebrow"><FileCheck2 size={15} /> Compliance alerts</div><h1>Document expiry control</h1><p>Track vehicle and driver documents with automatic 30-day expiry warnings.</p></div><button className="module-button module-button-primary" onClick={add}><Plus size={16} /> Add document</button></header>
    {error && <div className="module-inline-error" role="alert">{error}</div>}
    <section className="module-kpis">{[["Total documents", rows.length, FileCheck2], ["Expired", expired, AlertTriangle], ["Expiring in 30 days", expiring, CalendarClock], ["Valid", Math.max(0, rows.length - expired - expiring), ShieldCheck]].map(([label, value, Icon]) => <article className="module-kpi module-tone-blue" key={String(label)}><span className="module-kpi-icon"><Icon size={18} /></span><div className="module-kpi-copy"><span>{String(label)}</span><strong>{loading ? "—" : String(value)}</strong><small>Live compliance records</small></div></article>)}</section>
    <section className="module-data-panel"><div className="module-section-heading"><div><h2>Compliance register</h2><p>Expired documents appear first, followed by upcoming renewals.</p></div><span className="module-record-count">{rows.length} documents</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Document</th><th>Vehicle / driver</th><th>Number</th><th>Expiry</th><th>Status</th><th>Actions</th></tr></thead><tbody>{classified.sort((a, b) => (a.expires_on ?? "9999").localeCompare(b.expires_on ?? "9999")).map(row => <tr key={row.id}><td><strong>{row.document_type.toUpperCase()}</strong></td><td>{row.vehicles?.registration_number ?? row.drivers?.full_name ?? "Unassigned"}</td><td>{row.document_number ?? "—"}</td><td>{row.expires_on ? new Date(`${row.expires_on}T00:00:00`).toLocaleDateString("en-IN") : "No expiry"}</td><td><span className={`status-pill status-${row.expiryState}`}>{row.expiryState}</span></td><td><div className="live-record-actions"><button className="data-icon-button" onClick={() => edit(row)} aria-label="Edit document"><Pencil size={16} /></button><button className="data-icon-button live-delete-button" onClick={() => void remove(row)} aria-label="Delete document"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>{!loading && !rows.length && <div className="data-empty"><FileCheck2 size={22} /><strong>No compliance documents</strong><span>Add insurance, permit, fitness, PUC or licence expiry dates.</span></div>}</div></section>
    <AnimatePresence>{open && <div className="vehicle-modal-layer"><button className="modal-backdrop" aria-label="Close" onClick={() => setOpen(false)} /><section className="vehicle-dialog" role="dialog" aria-modal="true"><div className="vehicle-dialog-header"><div><span className="module-eyebrow">Compliance record</span><h2>{editing ? "Edit document" : "Add document"}</h2><p>Fleetora will calculate its expiry status automatically.</p></div><button className="data-icon-button" onClick={() => setOpen(false)}><X size={18} /></button></div><div className="vehicle-form-grid"><label><span>Belongs to</span><select value={form.owner_type} onChange={event => setForm({ ...form, owner_type: event.target.value, vehicle_id: "", driver_id: "" })}><option value="vehicle">Vehicle</option><option value="driver">Driver</option></select></label>{form.owner_type === "vehicle" ? <label><span>Vehicle</span><select value={form.vehicle_id} onChange={event => setForm({ ...form, vehicle_id: event.target.value })}><option value="">Select vehicle</option>{resources.vehicles.map(row => <option key={row.id} value={row.id}>{row.registration_number}</option>)}</select></label> : <label><span>Driver</span><select value={form.driver_id} onChange={event => setForm({ ...form, driver_id: event.target.value })}><option value="">Select driver</option>{resources.drivers.map(row => <option key={row.id} value={row.id}>{row.full_name}</option>)}</select></label>}<label><span>Document type</span><select value={form.document_type} onChange={event => setForm({ ...form, document_type: event.target.value })}>{types.map(type => <option key={type} value={type}>{type.toUpperCase()}</option>)}</select></label><label><span>Document number</span><input value={form.document_number} onChange={event => setForm({ ...form, document_number: event.target.value })} /></label><label><span>Issued on</span><input type="date" value={form.issued_on} onChange={event => setForm({ ...form, issued_on: event.target.value })} /></label><label><span>Expires on</span><input type="date" value={form.expires_on} onChange={event => setForm({ ...form, expires_on: event.target.value })} /></label></div><div className="vehicle-dialog-actions"><button className="module-button module-button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="module-button module-button-primary" disabled={saving || !valid} onClick={() => void save()}>{saving ? "Saving..." : "Save document"}</button></div></section></div>}</AnimatePresence>
  </motion.main>;
}
