"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { BarChart3, Download, Droplets, FileText, Fuel, Plus, Receipt, Search, Truck, Users, Wallet, X } from "lucide-react";
import { fleetoraApi } from "../lib/api";
import { supabase } from "../lib/supabase";

type Vehicle = { id: string; registration_number: string };
type Driver = { id: string; full_name: string; phone?: string | null; license_number?: string | null; status: string };
type Customer = { id: string; name: string; phone?: string | null; credit_limit?: number; status: string };
type Resources = { vehicles: Vehicle[]; drivers: Driver[]; customers: Customer[] };
type Trip = { id: string; trip_number: string; customer_id: string | null; vehicle_id: string | null; driver_id: string | null; origin: string; destination: string; status: string; rate_type: string; rate: number; quantity_tonnes: number; distance_km: number; freight_amount: number; scheduled_start_at: string | null; created_at: string; customers?: { name: string } | null; vehicles?: { registration_number: string } | null; drivers?: { full_name: string } | null };
type FuelEntry = { id: string; vehicle_id: string | null; trip_id: string | null; filled_at: string; litres: number; amount: number; odometer_km: number | null; station_name: string | null; payment_mode: string; receipt_path: string | null; vehicles?: { registration_number: string } | null; trips?: { trip_number: string } | null };
type Expense = { id: string; vehicle_id: string | null; trip_id: string | null; category: string; amount: number; payment_mode: string; expense_date: string; receipt_path: string | null; notes: string | null; automatic?: boolean; vehicles?: { registration_number: string } | null; trips?: { trip_number: string } | null };
type LedgerEntry = { id: string; customer_id: string; trip_id: string | null; entry_date: string; entry_type: "debit" | "credit"; amount: number; payment_mode: string | null; reference: string | null; customers?: { name: string } | null; trips?: { trip_number: string } | null };
type ReportData = { trips: Trip[]; fuel: FuelEntry[]; expenses: Expense[]; ledger: LedgerEntry[]; vehicles: Vehicle[]; drivers: Driver[]; customers: Customer[] };

const money = (value: number | string | null | undefined) => `INR ${Number(value ?? 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);
const tripStatus: Record<string, string> = { scheduled: "Planned", loading: "Planned", in_transit: "In Progress", delivered: "Completed", delayed: "In Progress", cancelled: "Cancelled" };

function Modal({ title, subtitle, children, saving, valid = true, onClose, onSave }: { title: string; subtitle: string; children: React.ReactNode; saving: boolean; valid?: boolean; onClose: () => void; onSave: () => void }) {
  return <div className="vehicle-modal-layer"><button className="modal-backdrop" aria-label="Close" onClick={onClose} /><section className="vehicle-dialog transport-dialog" role="dialog" aria-modal="true"><div className="vehicle-dialog-header"><div><span className="module-eyebrow">Live database</span><h2>{title}</h2><p>{subtitle}</p></div><button className="data-icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></div>{children}<div className="vehicle-dialog-actions"><button className="module-button module-button-secondary" onClick={onClose}>Cancel</button><button className="module-button module-button-primary" disabled={saving || !valid} onClick={onSave}>{saving ? "Saving..." : "Save"}</button></div></section></div>;
}

function PageHeader({ icon: Icon, eyebrow, title, subtitle, action, onAdd }: { icon: typeof Truck; eyebrow: string; title: string; subtitle: string; action: string; onAdd: () => void }) {
  return <header className="module-header"><div className="module-header-copy"><div className="module-eyebrow"><Icon size={15} /> {eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><button className="module-button module-button-primary" onClick={onAdd}><Plus size={16} /> {action}</button></header>;
}

function TripView() {
  const empty = { trip_number: "", customer_id: "", vehicle_id: "", driver_id: "", origin: "", destination: "", status: "scheduled", rate_type: "fixed", rate: "", quantity_tonnes: "", distance_km: "", scheduled_start_at: today(), notes: "" };
  const [records, setRecords] = useState<Trip[]>([]); const [resources, setResources] = useState<Resources>({ vehicles: [], drivers: [], customers: [] });
  const [form, setForm] = useState(empty); const [newParty, setNewParty] = useState({ name: "", phone: "", contact_name: "" }); const [tripExpense, setTripExpense] = useState({ enabled: false, category: "toll", amount: "", payment_mode: "cash", notes: "" }); const [editing, setEditing] = useState<string | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { try { const [trips, refs] = await Promise.all([fleetoraApi<Trip[]>("/trips?limit=100"), fleetoraApi<Resources>("/resources")]); setRecords(trips); setResources(refs); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not load trips."); } }
  useEffect(() => { void load(); }, []);
  const amount = form.rate_type === "per_ton" ? Number(form.rate) * Number(form.quantity_tonnes) : form.rate_type === "per_km" ? Number(form.rate) * Number(form.distance_km) : Number(form.rate);
  function add() { setEditing(null); setNewParty({ name: "", phone: "", contact_name: "" }); setTripExpense({ enabled: false, category: "toll", amount: "", payment_mode: "cash", notes: "" }); setForm({ ...empty, scheduled_start_at: today(), trip_number: `TRIP-${Date.now().toString().slice(-6)}` }); setOpen(true); }
  function edit(t: Trip) { setEditing(t.id); setTripExpense({ enabled: false, category: "toll", amount: "", payment_mode: "cash", notes: "" }); setForm({ trip_number: t.trip_number, customer_id: t.customer_id ?? "", vehicle_id: t.vehicle_id ?? "", driver_id: t.driver_id ?? "", origin: t.origin, destination: t.destination, status: t.status, rate_type: t.rate_type, rate: String(t.rate), quantity_tonnes: String(t.quantity_tonnes), distance_km: String(t.distance_km), scheduled_start_at: t.scheduled_start_at?.slice(0, 10) ?? today(), notes: "" }); setOpen(true); }
  async function save() { setSaving(true); try { let partyId = form.customer_id; if (partyId === "__new__") { const created = await fleetoraApi<Customer[]>("/customers", { method: "POST", body: JSON.stringify({ ...newParty, status: "active", credit_limit: 0, payment_terms_days: 30 }) }); partyId = created[0]?.id ?? ""; if (!partyId) throw new Error("The new party could not be created."); } const body = { ...form, customer_id: partyId || null, vehicle_id: form.vehicle_id || null, driver_id: form.driver_id || null, rate: Number(form.rate), quantity_tonnes: Number(form.quantity_tonnes), distance_km: Number(form.distance_km), scheduled_start_at: form.scheduled_start_at || null, actual_end_at: form.status === "delivered" ? new Date().toISOString() : null }; const saved = await fleetoraApi<Trip[]>(editing ? `/trips/${editing}` : "/trips", { method: editing ? "PATCH" : "POST", body: JSON.stringify(body) }); const tripId = editing ?? saved[0]?.id; if (tripExpense.enabled && tripExpense.amount && tripId) { await fleetoraApi("/expenses", { method: "POST", body: JSON.stringify({ trip_id: tripId, vehicle_id: form.vehicle_id || null, category: tripExpense.category, amount: Number(tripExpense.amount), payment_mode: tripExpense.payment_mode, expense_date: form.scheduled_start_at || today(), notes: tripExpense.notes || null }) }); } setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save trip."); } finally { setSaving(false); } }
  const completed = records.filter(r => r.status === "delivered").reduce((s, r) => s + Number(r.freight_amount), 0);
  return <motion.main className="module-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><PageHeader icon={Truck} eyebrow="Dispatch and income" title="Trip control" subtitle="Assign parties, trucks and drivers. Freight is calculated from the selected rate type." action="Create trip" onAdd={add} />
    <section className="module-kpis">{[["Trips", records.length], ["In progress", records.filter(r => r.status === "in_transit").length], ["Completed income", money(completed)], ["Outstanding trips", records.filter(r => r.status !== "delivered" && r.status !== "cancelled").length]].map(([label, value]) => <article className="module-kpi module-tone-blue" key={label}><span className="module-kpi-icon"><Truck size={18} /></span><div className="module-kpi-copy"><span>{label}</span><strong>{value}</strong><small>Live trip data</small></div></article>)}</section>
    {error && <div className="module-inline-error" role="alert">{error}</div>}
    <section className="module-data-panel"><div className="module-section-heading"><div><h2>Trip register</h2><p>Completing a trip automatically posts its amount to the party ledger as Udhar.</p></div><span className="module-record-count">{records.length} trips</span></div><div className="data-table-wrap"><table className="data-table enterprise-table"><thead><tr><th>Trip / Date</th><th>Party</th><th>Truck / Driver</th><th>Route</th><th>Rate</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{records.map(t => <tr key={t.id}><td><span className="data-primary-cell"><strong>{t.trip_number}</strong><small>{t.scheduled_start_at ? new Date(t.scheduled_start_at).toLocaleDateString("en-IN") : "Date not set"}</small></span></td><td>{t.customers?.name ?? "Not assigned"}</td><td><span className="data-primary-cell"><strong>{t.vehicles?.registration_number ?? "No truck"}</strong><small>{t.drivers?.full_name ?? "No driver"}</small></span></td><td>{t.origin} - {t.destination}</td><td>{t.rate_type.replace("_", " ")} @ {money(t.rate)}</td><td className="data-money data-money-positive">{money(t.freight_amount)}</td><td><span className={`status-pill status-${t.status.replace("_", "-")}`}>{tripStatus[t.status] ?? t.status}</span></td><td><button className="module-button module-button-secondary" onClick={() => edit(t)}>Edit</button></td></tr>)}</tbody></table>{!records.length && <div className="data-empty"><Truck size={22} /><strong>No trips yet</strong><span>Create your first trip.</span></div>}</div></section>
    <AnimatePresence>{open && <Modal title={editing ? "Edit trip" : "Create trip"} subtitle="Select a party, record the trip date, and optionally post a linked expense." saving={saving} valid={Boolean(form.trip_number && form.scheduled_start_at && form.customer_id && (form.customer_id !== "__new__" || newParty.name.trim()) && form.origin && form.destination && form.rate && (!tripExpense.enabled || tripExpense.amount))} onClose={() => setOpen(false)} onSave={() => void save()}>
      <div className="vehicle-form-grid transport-form">
        <label><span>Trip number</span><input value={form.trip_number} onChange={e => setForm({ ...form, trip_number: e.target.value })} /></label>
        <label><span>Trip date</span><input type="date" value={form.scheduled_start_at} onChange={e => setForm({ ...form, scheduled_start_at: e.target.value })} /></label>
        <label><span>Party option</span><select value={form.customer_id} onChange={e => setForm({ ...form, customer_id: e.target.value })}><option value="">Select existing party</option>{resources.customers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}<option value="__new__">+ Add new party</option></select></label>
        {form.customer_id === "__new__" && <><label><span>New party name</span><input value={newParty.name} onChange={e => setNewParty({ ...newParty, name: e.target.value })} placeholder="Required" /></label><label><span>Party phone</span><input value={newParty.phone} onChange={e => setNewParty({ ...newParty, phone: e.target.value })} /></label><label className="vehicle-form-wide"><span>Contact person</span><input value={newParty.contact_name} onChange={e => setNewParty({ ...newParty, contact_name: e.target.value })} /></label></>}
        <label><span>Truck</span><select value={form.vehicle_id} onChange={e => setForm({ ...form, vehicle_id: e.target.value })}><option value="">Select truck</option>{resources.vehicles.map(x => <option key={x.id} value={x.id}>{x.registration_number}</option>)}</select></label>
        <label><span>Driver</span><select value={form.driver_id} onChange={e => setForm({ ...form, driver_id: e.target.value })}><option value="">Select driver</option>{resources.drivers.map(x => <option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label>
        <label><span>Origin</span><input value={form.origin} onChange={e => setForm({ ...form, origin: e.target.value })} /></label>
        <label><span>Destination</span><input value={form.destination} onChange={e => setForm({ ...form, destination: e.target.value })} /></label>
        <label><span>Rate type</span><select value={form.rate_type} onChange={e => setForm({ ...form, rate_type: e.target.value })}><option value="fixed">Fixed</option><option value="per_ton">Per ton</option><option value="per_km">Per km</option></select></label>
        <label><span>Rate</span><input type="number" min="0" value={form.rate} onChange={e => setForm({ ...form, rate: e.target.value })} /></label>
        {form.rate_type === "per_ton" && <label><span>Weight (tonnes)</span><input type="number" min="0" value={form.quantity_tonnes} onChange={e => setForm({ ...form, quantity_tonnes: e.target.value })} /></label>}
        {form.rate_type === "per_km" && <label><span>Distance (km)</span><input type="number" min="0" value={form.distance_km} onChange={e => setForm({ ...form, distance_km: e.target.value })} /></label>}
        <label><span>Status</span><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="scheduled">Planned</option><option value="in_transit">In Progress</option><option value="delivered">Completed</option><option value="cancelled">Cancelled</option></select></label>
        <label className="vehicle-form-wide transport-expense-toggle"><input type="checkbox" checked={tripExpense.enabled} onChange={e => setTripExpense({ ...tripExpense, enabled: e.target.checked })} /><span>Add an expense linked to this trip</span></label>
        {tripExpense.enabled && <><label><span>Expense category</span><select value={tripExpense.category} onChange={e => setTripExpense({ ...tripExpense, category: e.target.value })}>{["fuel", "toll", "driver_allowance", "loading", "repair", "maintenance", "other"].map(x => <option key={x} value={x}>{x.replace("_", " ")}</option>)}</select></label><label><span>Expense amount</span><input type="number" min="0" value={tripExpense.amount} onChange={e => setTripExpense({ ...tripExpense, amount: e.target.value })} /></label><label><span>Payment mode</span><select value={tripExpense.payment_mode} onChange={e => setTripExpense({ ...tripExpense, payment_mode: e.target.value })}><option value="cash">Cash</option><option value="bank">Bank</option></select></label><label><span>Expense notes</span><input value={tripExpense.notes} onChange={e => setTripExpense({ ...tripExpense, notes: e.target.value })} /></label></>}
        <div className="transport-calculation"><span>Calculated trip amount</span><strong>{money(amount)}</strong></div>
      </div>
    </Modal>}</AnimatePresence>
  </motion.main>;
}

async function uploadReceipt(file: File | null) {
  if (!file || !supabase) return null;
  const { data } = await supabase.auth.getUser(); if (!data.user) throw new Error("Please sign in again.");
  const safe = file.name.replace(/[^a-zA-Z0-9._-]/g, "-"); const path = `${data.user.id}/${crypto.randomUUID()}-${safe}`;
  const uploaded = await supabase.storage.from("receipts").upload(path, file); if (uploaded.error) throw uploaded.error; return path;
}

function CostView({ kind }: { kind: "fuel" | "expenses" }) {
  const fuelMode = kind === "fuel"; const empty = fuelMode ? { vehicle_id: "", trip_id: "", filled_at: new Date().toISOString().slice(0, 16), litres: "", amount: "", odometer_km: "", station_name: "", payment_mode: "cash", notes: "" } : { vehicle_id: "", trip_id: "", expense_date: today(), category: "toll", amount: "", payment_mode: "cash", notes: "" };
  const [records, setRecords] = useState<(FuelEntry | Expense)[]>([]); const [resources, setResources] = useState<Resources>({ vehicles: [], drivers: [], customers: [] }); const [trips, setTrips] = useState<Trip[]>([]); const [form, setForm] = useState<Record<string, string>>(empty); const [file, setFile] = useState<File | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { try { const [rows, refs, tripRows, fuelRows] = await Promise.all([fleetoraApi<(FuelEntry | Expense)[]>(`/${kind}`), fleetoraApi<Resources>("/resources"), fleetoraApi<Trip[]>("/trips?limit=100"), fuelMode ? Promise.resolve([] as FuelEntry[]) : fleetoraApi<FuelEntry[]>("/fuel")]); const automaticFuel: Expense[] = fuelRows.map(f => ({ id: `fuel-${f.id}`, vehicle_id: f.vehicle_id, trip_id: f.trip_id, category: "fuel", amount: f.amount, payment_mode: f.payment_mode, expense_date: f.filled_at.slice(0, 10), receipt_path: f.receipt_path, notes: `${f.litres} L${f.station_name ? ` at ${f.station_name}` : ""}`, automatic: true, vehicles: f.vehicles, trips: f.trips })); const combined = fuelMode ? rows : [...(rows as Expense[]), ...automaticFuel].sort((a, b) => b.expense_date.localeCompare(a.expense_date)); setRecords(combined); setResources(refs); setTrips(tripRows); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not load entries."); } }
  useEffect(() => { void load(); }, [kind]);
  async function save() { setSaving(true); try { const receipt_path = await uploadReceipt(file); const body = { ...form, vehicle_id: form.vehicle_id || null, trip_id: form.trip_id || null, litres: fuelMode ? Number(form.litres) : undefined, odometer_km: fuelMode && form.odometer_km ? Number(form.odometer_km) : null, amount: Number(form.amount), receipt_path }; await fleetoraApi(`/${kind}`, { method: "POST", body: JSON.stringify(body) }); setOpen(false); setForm(empty); setFile(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save entry."); } finally { setSaving(false); } }
  const total = records.reduce((s, r) => s + Number(r.amount), 0); const litres = fuelMode ? (records as FuelEntry[]).reduce((s, r) => s + Number(r.litres), 0) : 0;
  const truckStats = useMemo(() => resources.vehicles.map(v => { const rows = records.filter(r => r.vehicle_id === v.id); return { name: v.registration_number, amount: rows.reduce((s, r) => s + Number(r.amount), 0), count: rows.length, litres: fuelMode ? (rows as FuelEntry[]).reduce((s, r) => s + Number(r.litres), 0) : 0 }; }).filter(x => x.count), [records, resources, fuelMode]);
  return <motion.main className="module-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><PageHeader icon={fuelMode ? Fuel : Receipt} eyebrow={fuelMode ? "Fuel intelligence" : "Cost control"} title={fuelMode ? "Fuel management" : "Expense management"} subtitle={fuelMode ? "Record every fill-up and compare fuel cost by truck." : "Categorize cash and bank expenses with truck, trip and receipt links."} action={fuelMode ? "Add fuel" : "Add expense"} onAdd={() => setOpen(true)} />
    <section className="module-kpis">{[[fuelMode ? "Fuel cost" : "Total expenses", money(total)], [fuelMode ? "Litres filled" : "Cash paid", fuelMode ? litres.toLocaleString("en-IN") : money(records.filter(r => r.payment_mode === "cash").reduce((s, r) => s + Number(r.amount), 0))], ["Bank paid", money(records.filter(r => r.payment_mode === "bank").reduce((s, r) => s + Number(r.amount), 0))], ["Entries", records.length]].map(([label, value]) => <article className="module-kpi module-tone-amber" key={label}><span className="module-kpi-icon"><Droplets size={18} /></span><div className="module-kpi-copy"><span>{label}</span><strong>{value}</strong><small>Live records</small></div></article>)}</section>{error && <div className="module-inline-error">{error}</div>}
    <div className="module-content-grid"><section className="module-data-panel"><div className="module-section-heading"><div><h2>{fuelMode ? "Fuel register" : "Expense register"}</h2><p>{fuelMode ? "Truck-specific fuel entries" : "Manual expenses and fuel entries are combined automatically"}</p></div><span className="module-record-count">{records.length} entries</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Truck</th><th>{fuelMode ? "Litres / Station" : "Category"}</th><th>Mode</th><th>Amount</th><th>Receipt</th></tr></thead><tbody>{records.map(r => <tr key={r.id}><td>{new Date(fuelMode ? (r as FuelEntry).filled_at : (r as Expense).expense_date).toLocaleDateString("en-IN")}</td><td>{r.vehicles?.registration_number ?? "General"}</td><td>{fuelMode ? `${(r as FuelEntry).litres} L / ${(r as FuelEntry).station_name ?? "-"}` : <span className="data-primary-cell"><strong>{(r as Expense).category.replace("_", " ")}</strong>{(r as Expense).automatic && <small>Automatic from fuel</small>}</span>}</td><td>{r.payment_mode}</td><td>{money(r.amount)}</td><td>{r.receipt_path ? <span className="status-pill status-completed"><FileText size={12} /> Attached</span> : "-"}</td></tr>)}</tbody></table>{!records.length && <div className="data-empty"><Receipt size={22} /><strong>No entries yet</strong></div>}</div></section><aside className="panel-insight"><div className="panel-insight-heading"><Truck size={16} /> Per-truck analytics</div><h2>{fuelMode ? "Fuel consumption and cost" : "Vehicle expense allocation"}</h2><div className="panel-insight-list">{truckStats.slice(0, 8).map(x => <div className="panel-insight-item" key={x.name}><span>{x.name}</span><strong>{fuelMode ? `${x.litres.toFixed(1)} L / ${money(x.amount)}` : money(x.amount)}</strong></div>)}</div></aside></div>
    <AnimatePresence>{open && <Modal title={fuelMode ? "Record fuel" : "Record expense"} subtitle="Attach an image or PDF receipt up to 10 MB." saving={saving} valid={Boolean(form.amount && (fuelMode ? form.vehicle_id && form.litres : form.category))} onClose={() => setOpen(false)} onSave={() => void save()}><div className="vehicle-form-grid transport-form"><label><span>Truck (optional for general expense)</span><select value={form.vehicle_id} onChange={e => setForm({ ...form, vehicle_id: e.target.value })}><option value="">General / select truck</option>{resources.vehicles.map(v => <option key={v.id} value={v.id}>{v.registration_number}</option>)}</select></label><label><span>Trip (optional)</span><select value={form.trip_id} onChange={e => setForm({ ...form, trip_id: e.target.value })}><option value="">No trip</option>{trips.map(t => <option key={t.id} value={t.id}>{t.trip_number}</option>)}</select></label>{fuelMode ? <><label><span>Litres</span><input type="number" min="0" value={form.litres} onChange={e => setForm({ ...form, litres: e.target.value })} /></label><label><span>Odometer km</span><input type="number" min="0" value={form.odometer_km} onChange={e => setForm({ ...form, odometer_km: e.target.value })} /></label><label><span>Station</span><input value={form.station_name} onChange={e => setForm({ ...form, station_name: e.target.value })} /></label><label><span>Filled at</span><input type="datetime-local" value={form.filled_at} onChange={e => setForm({ ...form, filled_at: e.target.value })} /></label></> : <><label><span>Category</span><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{["fuel", "toll", "driver_allowance", "loading", "repair", "maintenance", "office", "salary", "other"].map(x => <option key={x}>{x}</option>)}</select></label><label><span>Expense date</span><input type="date" value={form.expense_date} onChange={e => setForm({ ...form, expense_date: e.target.value })} /></label></>}<label><span>Amount</span><input type="number" min="0" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /></label><label><span>Payment mode</span><select value={form.payment_mode} onChange={e => setForm({ ...form, payment_mode: e.target.value })}><option value="cash">Cash</option><option value="bank">Bank</option></select></label><label className="vehicle-form-wide"><span>Bill / receipt</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => setFile(e.target.files?.[0] ?? null)} /></label><label className="vehicle-form-wide"><span>Notes</span><input value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label></div></Modal>}</AnimatePresence>
  </motion.main>;
}

function DirectoryView({ kind }: { kind: "drivers" | "customers" }) {
  const driverMode = kind === "drivers"; const blank = driverMode ? { full_name: "", phone: "", license_number: "", license_expiry: "", status: "available" } : { name: "", phone: "", contact_name: "", email: "", credit_limit: "0", payment_terms_days: "30", status: "active" };
  const [rows, setRows] = useState<(Driver | Customer)[]>([]); const [ledgerRows, setLedgerRows] = useState<LedgerEntry[]>([]); const [form, setForm] = useState<Record<string, string>>(blank); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { try { const [directory, ledger] = await Promise.all([fleetoraApi<(Driver | Customer)[]>(`/${kind}?limit=100`), driverMode ? Promise.resolve([] as LedgerEntry[]) : fleetoraApi<LedgerEntry[]>("/ledger")]); setRows(directory); setLedgerRows(ledger); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not load records."); } } useEffect(() => { void load(); }, [kind]);
  const customerBalance = (customerId: string) => ledgerRows.filter(row => row.customer_id === customerId).reduce((sum, row) => sum + (row.entry_type === "debit" ? Number(row.amount) : -Number(row.amount)), 0);
  async function save() { setSaving(true); try { const body = driverMode ? form : { ...form, credit_limit: Number(form.credit_limit), payment_terms_days: Number(form.payment_terms_days) }; await fleetoraApi(`/${kind}`, { method: "POST", body: JSON.stringify(body) }); setOpen(false); setForm(blank); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save."); } finally { setSaving(false); } }
  return <motion.main className="module-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
    <PageHeader icon={driverMode ? Users : Wallet} eyebrow={driverMode ? "Workforce" : "Party accounts"} title={driverMode ? "Driver workforce" : "Customer and party accounts"} subtitle={driverMode ? "Drivers added here can be assigned to trips." : "Parties added here receive completed trip amounts in their ledger."} action={driverMode ? "Add driver" : "Add party"} onAdd={() => setOpen(true)} />
    {error && <div className="module-inline-error">{error}</div>}
    <section className="module-data-panel"><div className="module-section-heading"><div><h2>{driverMode ? "Driver directory" : "Party directory"}</h2><p>{driverMode ? "Live operational master data" : "Live credit limits and ledger balances"}</p></div><span className="module-record-count">{rows.length} records</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Phone</th><th>{driverMode ? "License" : "Credit limit"}</th>{!driverMode && <th>Ledger / Udhar</th>}<th>Status</th></tr></thead><tbody>{rows.map(row => { const balance = driverMode ? 0 : customerBalance(row.id); return <tr key={row.id}><td><strong>{driverMode ? (row as Driver).full_name : (row as Customer).name}</strong></td><td>{row.phone ?? "-"}</td><td>{driverMode ? (row as Driver).license_number ?? "-" : money((row as Customer).credit_limit)}</td>{!driverMode && <td className={balance > 0 ? "data-money-negative" : "data-money-positive"}><strong>{money(balance)}</strong></td>}<td><span className={`status-pill status-${row.status.replace("_", "-")}`}>{row.status}</span></td></tr>; })}</tbody></table></div></section>
    <AnimatePresence>{open && <Modal title={driverMode ? "Add driver" : "Add party"} subtitle="This record will be available in trip assignment." saving={saving} valid={Boolean(driverMode ? form.full_name : form.name)} onClose={() => setOpen(false)} onSave={() => void save()}><div className="vehicle-form-grid transport-form"><label><span>Name</span><input value={driverMode ? form.full_name : form.name} onChange={e => setForm({ ...form, [driverMode ? "full_name" : "name"]: e.target.value })} /></label><label><span>Phone</span><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label>{driverMode ? <><label><span>License number</span><input value={form.license_number} onChange={e => setForm({ ...form, license_number: e.target.value })} /></label><label><span>License expiry</span><input type="date" value={form.license_expiry} onChange={e => setForm({ ...form, license_expiry: e.target.value })} /></label></> : <><label><span>Contact person</span><input value={form.contact_name} onChange={e => setForm({ ...form, contact_name: e.target.value })} /></label><label><span>Email</span><input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label><span>Credit limit</span><input type="number" value={form.credit_limit} onChange={e => setForm({ ...form, credit_limit: e.target.value })} /></label><label><span>Payment terms (days)</span><input type="number" value={form.payment_terms_days} onChange={e => setForm({ ...form, payment_terms_days: e.target.value })} /></label></>}</div></Modal>}</AnimatePresence>
  </motion.main>;
}

function exportExcel(data: Array<Record<string, string | number>>, name: string) {
  const cols = Object.keys(data[0] ?? { Message: "No records" }); const rows = data.length ? data : [{ Message: "No records" }];
  const esc = (v: unknown) => String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Fleetora"><Table><Row>${cols.map(c => `<Cell><Data ss:Type="String">${esc(c)}</Data></Cell>`).join("")}</Row>${rows.map(r => `<Row>${cols.map(c => `<Cell><Data ss:Type="String">${esc(r[c])}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet></Workbook>`;
  const url = URL.createObjectURL(new Blob([xml], { type: "application/vnd.ms-excel" })); const a = document.createElement("a"); a.href = url; a.download = `${name}.xls`; a.click(); URL.revokeObjectURL(url);
}

function ReportsView({ ledgerOnly = false }: { ledgerOnly?: boolean }) {
  const [data, setData] = useState<ReportData | null>(null); const [month, setMonth] = useState(today().slice(0, 7)); const [payment, setPayment] = useState({ customer_id: "", amount: "", payment_mode: "bank", reference: "", entry_date: today() }); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { try { setData(await fleetoraApi<ReportData>("/reports")); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not load reports."); } } useEffect(() => { void load(); }, []);
  const trips = (data?.trips ?? []).filter(t => t.created_at.startsWith(month)); const fuel = (data?.fuel ?? []).filter(x => x.filled_at.startsWith(month)); const expenses = (data?.expenses ?? []).filter(x => x.expense_date.startsWith(month)); const revenue = trips.filter(t => t.status === "delivered").reduce((s, t) => s + Number(t.freight_amount), 0); const costs = fuel.reduce((s, x) => s + Number(x.amount), 0) + expenses.reduce((s, x) => s + Number(x.amount), 0); const ledger = data?.ledger ?? [];
  const partyBalances = useMemo(() => (data?.customers ?? []).map(c => { const rows = ledger.filter(x => x.customer_id === c.id); return { id: c.id, name: c.name, debit: rows.filter(x => x.entry_type === "debit").reduce((s, x) => s + Number(x.amount), 0), credit: rows.filter(x => x.entry_type === "credit").reduce((s, x) => s + Number(x.amount), 0) }; }).filter(x => x.debit || x.credit), [data, ledger]);
  const truckRows = (data?.vehicles ?? []).map(v => { const vt = trips.filter(t => t.vehicle_id === v.id); const income = vt.reduce((s, t) => s + Number(t.freight_amount), 0); const cost = fuel.filter(x => x.vehicle_id === v.id).reduce((s, x) => s + Number(x.amount), 0) + expenses.filter(x => x.vehicle_id === v.id).reduce((s, x) => s + Number(x.amount), 0); return { Truck: v.registration_number, Trips: vt.length, Income: income, Cost: cost, Profit: income - cost }; });
  const driverRows = (data?.drivers ?? []).map(d => { const dt = trips.filter(t => t.driver_id === d.id); return { Driver: d.full_name, Trips: dt.length, Completed: dt.filter(t => t.status === "delivered").length, Income: dt.reduce((s, t) => s + Number(t.freight_amount), 0) }; });
  async function recordPayment() { setSaving(true); try { await fleetoraApi("/ledger/payments", { method: "POST", body: JSON.stringify({ ...payment, amount: Number(payment.amount) }) }); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not record payment."); } finally { setSaving(false); } }
  return <motion.main className="module-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><PageHeader icon={ledgerOnly ? Wallet : BarChart3} eyebrow="Finance intelligence" title={ledgerOnly ? "Party ledger and Udhar" : "Transport reports"} subtitle="Completed trip income, costs, profit, truck and driver performance from live data." action="Record payment" onAdd={() => setOpen(true)} />{error && <div className="module-inline-error">{error}</div>}{!ledgerOnly && <><div className="filter-bar report-filter"><label><span>Report month</span><input type="month" value={month} onChange={e => setMonth(e.target.value)} /></label><button className="module-button module-button-secondary" onClick={() => exportExcel([{ Month: month, Revenue: revenue, Costs: costs, Profit: revenue - costs }, ...truckRows], `Fleetora-report-${month}`)}><Download size={15} /> Export Excel</button></div><section className="module-kpis">{[["Trip income", money(revenue)], ["Fuel + expenses", money(costs)], ["Net profit / loss", money(revenue - costs)], ["Completed trips", trips.filter(t => t.status === "delivered").length]].map(([label, value]) => <article className="module-kpi module-tone-emerald" key={label}><span className="module-kpi-icon"><BarChart3 size={18} /></span><div className="module-kpi-copy"><span>{label}</span><strong>{value}</strong><small>{month}</small></div></article>)}</section><div className="report-panels"><section className="module-data-panel"><div className="module-section-heading"><div><h2>Truck-wise performance</h2><p>Income, operating cost and profit</p></div><button className="module-button module-button-secondary" onClick={() => exportExcel(truckRows, `Truck-report-${month}`)}>Excel</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Truck</th><th>Trips</th><th>Income</th><th>Cost</th><th>Profit</th></tr></thead><tbody>{truckRows.map(r => <tr key={r.Truck}><td>{r.Truck}</td><td>{r.Trips}</td><td>{money(r.Income)}</td><td>{money(r.Cost)}</td><td className={r.Profit >= 0 ? "data-money-positive" : "data-money-negative"}>{money(r.Profit)}</td></tr>)}</tbody></table></div></section><section className="module-data-panel"><div className="module-section-heading"><div><h2>Driver-wise report</h2><p>Trips, completion and linked revenue</p></div><button className="module-button module-button-secondary" onClick={() => exportExcel(driverRows, `Driver-report-${month}`)}>Excel</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Driver</th><th>Trips</th><th>Completed</th><th>Income</th></tr></thead><tbody>{driverRows.map(r => <tr key={r.Driver}><td>{r.Driver}</td><td>{r.Trips}</td><td>{r.Completed}</td><td>{money(r.Income)}</td></tr>)}</tbody></table></div></section></div></>}
    <section className="module-data-panel"><div className="module-section-heading"><div><h2>Party ledger / Udhar report</h2><p>Trip debits minus payments received</p></div><button className="module-button module-button-secondary" onClick={() => exportExcel(partyBalances.map(x => ({ Party: x.name, TripAmount: x.debit, Received: x.credit, Udhar: x.debit - x.credit })), "Party-ledger")}>Export ledger</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Party</th><th>Completed trip amount</th><th>Payments received</th><th>Udhar balance</th></tr></thead><tbody>{partyBalances.map(x => <tr key={x.id}><td><strong>{x.name}</strong></td><td>{money(x.debit)}</td><td>{money(x.credit)}</td><td className={x.debit - x.credit > 0 ? "data-money-negative" : "data-money-positive"}><strong>{money(x.debit - x.credit)}</strong></td></tr>)}</tbody></table>{!partyBalances.length && <div className="data-empty"><Wallet size={22} /><strong>No ledger entries</strong><span>Complete a trip to create the party debit automatically.</span></div>}</div></section>
    <section className="module-data-panel"><div className="module-section-heading"><div><h2>Ledger transactions</h2><p>Trip debits and received payments with their recorded dates</p></div><span className="module-record-count">{ledger.length} entries</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Party</th><th>Reference / Trip</th><th>Debit</th><th>Payment received</th><th>Mode</th></tr></thead><tbody>{ledger.map(entry => <tr key={entry.id}><td>{new Date(entry.entry_date).toLocaleDateString("en-IN")}</td><td><strong>{entry.customers?.name ?? "-"}</strong></td><td>{entry.reference ?? entry.trips?.trip_number ?? "-"}</td><td>{entry.entry_type === "debit" ? money(entry.amount) : "-"}</td><td className="data-money-positive">{entry.entry_type === "credit" ? money(entry.amount) : "-"}</td><td>{entry.payment_mode ?? "-"}</td></tr>)}</tbody></table>{!ledger.length && <div className="data-empty"><Wallet size={22} /><strong>No ledger transactions yet</strong></div>}</div></section>
    <AnimatePresence>{open && <Modal title="Record party payment" subtitle="This credit reduces the party's Udhar balance." saving={saving} valid={Boolean(payment.customer_id && payment.amount && payment.entry_date)} onClose={() => setOpen(false)} onSave={() => void recordPayment()}><div className="vehicle-form-grid transport-form"><label><span>Party</span><select value={payment.customer_id} onChange={e => setPayment({ ...payment, customer_id: e.target.value })}><option value="">Select party</option>{data?.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Amount received</span><input type="number" min="0" value={payment.amount} onChange={e => setPayment({ ...payment, amount: e.target.value })} /></label><label><span>Payment mode</span><select value={payment.payment_mode} onChange={e => setPayment({ ...payment, payment_mode: e.target.value })}><option value="cash">Cash</option><option value="bank">Bank</option></select></label><label><span>Payment date</span><input type="date" value={payment.entry_date} onChange={e => setPayment({ ...payment, entry_date: e.target.value })} /></label><label className="vehicle-form-wide"><span>Reference</span><input value={payment.reference} onChange={e => setPayment({ ...payment, reference: e.target.value })} /></label></div></Modal>}</AnimatePresence>
  </motion.main>;
}

export function TransportAccountingView({ route }: { route: string }) {
  const module = route.toLowerCase().split("/")[0];
  if (module === "trips") return <TripView />;
  if (module === "fuel") return <CostView kind="fuel" />;
  if (module === "expenses") return <CostView kind="expenses" />;
  if (module === "reports") return <ReportsView />;
  if (module === "accounting") return <ReportsView ledgerOnly />;
  if (module === "drivers" || module === "customers") return <DirectoryView kind={module} />;
  return null;
}

export const transportAccountingRoutes = new Set(["trips", "fuel", "expenses", "reports", "accounting", "drivers", "customers"]);
